export const orders = [
    {
      id: 1,
      img: "/1.jpg",
      customerName: "aaaaa",
      email: "...@gmail.com",
      phoneNumber: "13234",
      customerAddress: "aaaaaaa",
      price: "$250.99",
      date: "01.02.2023",
      time: "12:12",
    },
    {
        id: 2,
        img: "/2.jpg",
        customerName: "bbbbb",
        customerNumber: "12134",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 3,
        img: "/3.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 4,
        img: "/4.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 5,
        img: "/5.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 6,
        img: "/6.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 7,
        img: "/7.jpg",
        customerName: "Paaaaaaa",
        customerNumber: "white",
        customerAddress: "aaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 8,
        img: "/8.jpg",
        customerName: "aaaaaaaion",
        customerNumber: "white",
        customerAddress: "Soaaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 9,
        img: "/9.jpg",
        customerName: "aaaaaaa",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
      {
        id: 10,
        img: "/10.jpg",
        customerName: "aaaaaaan",
        customerNumber: "white",
        customerAddress: "Saaaaaaa",
        price: "$250.99",
        date: "01.02.2023",
        time: "12:12",
      },
    
  ];
  export const singleProduct = {
    id: 1,
    title: ": AAAAAAAA",
    img: "/1.jpg",
    info: {
      productId: ": 1",
      price: ": $250.99",
      Restraurent: ": Soo",
      CustomerName: ": Simolie",
      Address: ": 23rd road",
      MobileNo: ": 2222222",
    },
  };